name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu machine

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Fetches the repo code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Enables better Docker builds

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERTOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest --push .
